### PR TITLE
ci: use shallow fetch and no tags

### PR DESCRIPTION
**Pull request by fabiobaltieri**
Add a couple flags to west update to do shallow fetch for both the main repo and modules, and don't fetch any tags. Should speed things up a bit by only fetching the target version code for all modules.

### CODE REVIEW

**Comment by fabiobaltieri** [comment]
Cut "Initialize" time in half.

**Review by gmarull — APPROVED** [review]
is there any reason this isn't the default in west?

**Comment by fabiobaltieri** [comment]
> is there any reason this isn't the default in west?

I don't think it's a good idea to have it default, if you are doing development you probably want the whole history plus you wouldn't expect west to mess up with git defaults. For CI it makes no sense though.

**Comment by henrikbrixandersen** [comment]
> > is there any reason this isn't the default in west?
> 
> 
> 
> I don't think it's a good idea to have it default, if you are doing development you probably want the whole history plus you wouldn't expect west to mess up with git defaults. For CI it makes no sense though.

Agered.

**Pull request merged**
