### PR TITLE
Updates for HWMv2

### PR DESCRIPTION
**Pull request by gmarull**

### CODE REVIEW

**Review by nordicjm — APPROVED** [review]

**Review by fabiobaltieri — APPROVED** [review]

**Review by stephanosio — CHANGES_REQUESTED** [review]
DNM until HWMv2 is mainlined

**Review by tejlmand — APPROVED** [review]

**Comment by henrikbrixandersen** [comment]
@stephanosio Please revisit.

**Comment by stephanosio** [comment]
> @stephanosio Please revisit.

The PR still contains a commit that says DNM.

**Comment by carlescufi** [comment]
Superseeded by #58

**Pull request closed without merging**
